#!/usr/bin/env bash

# This script generates a hyprlock config file with Pywal colors.

# Source the Pywal colors.sh file
if [ -f "$HOME/.cache/wal/colors.sh" ]; then
    . "$HOME/.cache/wal/colors.sh"
else
    echo "Pywal colors not found. Please run 'wal -i <image>' first." >&2
    exit 1
fi

# Define the output file for Hyprlock
HYPRLOCK_COLORS_FILE="$HOME/.config/hypr/hyprlock_colors.conf"

# Write the Pywal colors into the Hyprlock config file
# The `rgb()` format is required, so we remove the leading '#' from the hex codes
echo "# Pywal colors for Hyprlock - Generated by hyprlock-pywal-colors.sh" > "$HYPRLOCK_COLORS_FILE"
echo "\$hyprlock_accent = rgb(${color4:1})" >> "$HYPRLOCK_COLORS_FILE"
echo "\$hyprlock_background = rgb(${background:1})" >> "$HYPRLOCK_COLORS_FILE"
echo "\$hyprlock_foreground = rgb(${foreground:1})" >> "$HYPRLOCK_COLORS_FILE"
echo "\$hyprlock_red = rgb(${color1:1})" >> "$HYPRLOCK_COLORS_FILE"
echo "\$hyprlock_yellow = rgb(${color3:1})" >> "$HYPRLOCK_COLORS_FILE"
echo "\$hyprlock_green = rgb(${color2:1})" >> "$HYPRLOCK_COLORS_FILE"
