#!/usr/bin/env bash
# hyprlock-pywal-colors.sh
# Generates a pywal color override file for Hyprlock

# Source pywal colors
if [ -f "$HOME/.cache/wal/colors.sh" ]; then
    . "$HOME/.cache/wal/colors.sh"
else
    echo "Pywal colors not found." >&2
    exit 1
fi

# Strip the '#' from hex colors for hyprlock's rgba() format
strip() { echo "${1#\#}"; }

OUT="$HOME/.cache/wal/hyprlock-colors.conf"

cat > "$OUT" <<EOF
# Auto-generated by hyprlock-pywal-colors.sh — do not edit manually

\$wal_background  = rgba($(strip $color0)ee)
\$wal_foreground  = rgba($(strip $color7)ff)
\$wal_accent      = rgba($(strip $color1)ff)
\$wal_highlight   = rgba($(strip $color2)ff)
\$wal_inactive    = rgba($(strip $color8)aa)
\$wal_border      = rgba($(strip $color4)ff)
EOF

echo "Hyprlock pywal colors written to $OUT"
