#!/usr/bin/env bash

# This script reads Pywal colors and updates Hyprland border colors.
# It assumes colors.json is generated by Pywal.

PYWAL_CACHE_DIR="$HOME/.cache/wal"
COLORS_JSON="$PYWAL_CACHE_DIR/colors.json"
HYPR_COLORS_CONF="$HOME/.config/hypr/colors.conf"

# Check if colors.json exists
if [ ! -f "$COLORS_JSON" ]; then
    echo "Error: Pywal colors.json not found at '$COLORS_JSON'. Run 'wal -i' first."
    exit 1
fi

# Function to extract a color and convert to rgba(RRGGBBAA)
# Takes the JSON path (e.g., .special.foreground, .colors.color4) and an optional alpha (00-ff)
get_rgba_color() {
    local json_path="$1"
    local alpha="${2:-ff}" # Default to fully opaque (ff) if no alpha provided

    # Extract hex color (e.g., #RRGGBB)
    local hex_color=$(jq -r "$json_path" "$COLORS_JSON")

    if [ -z "$hex_color" ]; then
        echo "Error: Could not extract color from JSON path: $json_path" >&2
        exit 1
    fi

    # Remove the '#' prefix
    local rgb_part="${hex_color#\#}"

    # Construct the rgba string
    echo "rgba(${rgb_part}${alpha})"
}

# Get colors from Pywal's JSON
# You can choose which colors to use for active/inactive borders.
# Common choices are color4 (blue), color1 (red), or special.foreground/background
ACTIVE_BORDER_COLOR=$(get_rgba_color ".colors.color4" "ff") # Example: Pywal's color4 (blue) fully opaque
INACTIVE_BORDER_COLOR=$(get_rgba_color ".special.background" "aa") # Example: Pywal's background with 66% opacity

if [ -z "$ACTIVE_BORDER_COLOR" ] || [ -z "$INACTIVE_BORDER_COLOR" ]; then
    echo "Failed to get one or more colors. Exiting."
    exit 1
fi

echo "Updating $HYPR_COLORS_CONF with new border colors:"
echo "Active: $ACTIVE_BORDER_COLOR"
echo "Inactive: $INACTIVE_BORDER_COLOR"

# Write the new color configuration to the sourced file
cat <<EOF > "$HYPR_COLORS_CONF"
# This file is automatically generated by Pywal integration script. Do not edit manually.
general {
    col.active_border = $ACTIVE_BORDER_COLOR
    col.inactive_border = $INACTIVE_BORDER_COLOR
}
EOF

# Reload Hyprland to apply the new colors
echo "Reloading Hyprland..."
hyprctl reload

echo "Hyprland border colors updated successfully."
